apiVersion: v1
kind: Namespace
metadata:
  name: mq-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: mq-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "xxxxxxxxxx"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbit"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbit"
            - name: TZ
              value: "Europe/Moscow"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mq-test
spec:
  type: NodePort
  ports:
    - nodePort: 30400
      port: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mq-test
spec:
  type: NodePort
  ports:
    - nodePort: 30401
      port: 5672
  selector:
    app: rabbitmq